# Generated by Django 4.0.6 on 2022-07-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
