# Generated by Django 4.0.6 on 2022-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0004_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
