# Generated by Django 4.0.6 on 2022-07-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0007_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
