# Generated by Django 4.0.6 on 2022-07-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0008_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
