# Generated by Django 4.0.6 on 2022-07-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0017_alter_article_article_type_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('Top', 'Top'), ('Bottoms', 'Btm'), ('Dress', 'Dress'), ('Jumpsuit/Romper', 'Jmpst'), ('Sweater', 'Swtr'), ('Cardigan', 'Crdgn'), ('Outerwear', 'Otrwr'), ('Bodysuit', 'Bdyst'), ('Lingerie', 'Lngre'), ('Shoes', 'Shoes'), ('Accessory', 'Accsry'), ('Socks/Tights', 'Socks')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Loungewear', 'Lngewr'), ('Casual', 'Csul'), ('Formal', 'Frml'), ('Party', 'Prty'), ('Work', 'Wrk')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='article',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Orange', 'Ornge'), ('Yellow', 'Ylw'), ('Blue', 'Blue'), ('Green', 'Grn'), ('White', 'White'), ('Beige', 'Bge'), ('Cream', 'Cream'), ('Black', 'Blk'), ('Purple', 'Prple'), ('Pink', 'Pnk'), ('Gray', 'Gray'), ('Brown', 'Brwn'), ('Tan', 'Tan'), ('Multi', 'Mlti')], default='', max_length=15),
        ),
    ]
