# Generated by Django 4.0.6 on 2022-07-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0021_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='article',
        ),
        migrations.AddField(
            model_name='favorite',
            name='article_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles_1', to='capsule.article'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='article_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles_2', to='capsule.article'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='article_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles_3', to='capsule.article'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
