# Generated by Django 4.0.6 on 2022-07-30 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Green', 'Green'), ('White', 'White'), ('Beige', 'Beige'), ('Cream', 'Cream'), ('Black', 'Black'), ('Purple', 'Purple'), ('Pink', 'Pink'), ('Gray', 'Gray'), ('Brown', 'Brown'), ('Tan', 'Tan'), ('Multi', 'Multi')], default='Color.RED', max_length=15)),
                ('article_type', models.CharField(choices=[('Top', 'Top'), ('Bottoms', 'Bottoms'), ('Dress', 'Dress'), ('Jumpsuit/Romper', 'Jumpsuit/Romper'), ('Sweater', 'Sweater'), ('Cardigan', 'Cardigan'), ('Outerwear', 'Outerwear'), ('Bodysuit', 'Bodysuit'), ('Lingerie', 'Lingerie'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory'), ('Socks/Tights', 'Socks/Tights')], default='ArticleType.TOP', max_length=15)),
                ('category', models.CharField(choices=[('Loungewear', 'Loungewear'), ('Casual', 'Casual'), ('Formal', 'Formal'), ('Party', 'Party'), ('Work', 'Work')], default='CategoryType.WRK', max_length=15)),
                ('brand', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('article_1', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles_1', to='capsule.article')),
                ('article_2', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles_2', to='capsule.article')),
                ('article_3', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='articles_3', to='capsule.article')),
            ],
        ),
    ]
